[spins.lxqt.x86_64]
fas = [ "lupinix", "zsun" ]
maintainers = [ "Christian Dersch", "Zamir SUN" ]
[spins.lxqt.armhfp]
fas = [ "lupinix", "zsun" ]
maintainers = [ "Christian Dersch", "Zamir SUN" ]

[spins.xfce.x86_64]
fas = [ "nonamedotc", "kevin", "maxamillion" ]
maintainers = [ "Mukundan Ragavan", "Kevin Fenzi", "Adam Miller" ]
[spins.xfce.armhfp]
fas = [ "nonamedotc", "kevin", "maxamillion" ]
maintainers = [ "Mukundan Ragavan", "Kevin Fenzi", "Adam Miller" ]

[spins.kde.x86_64]
fas = [ "rdieter", "svahl" ]
maintainers = [ "Rex Dieter", "Sebastian Vahl" ]

[spins.cinnamon.x86_64]
fas = [ "grinnz" ]
maintainers = [ "Dan Book" ]

[spins.lxde.x86_64]
fas = [ "cwickert", "mtasaka" ]
maintainers = [ "Christoph Wickert", "Mamoru TASAKA" ]
[spins.lxde.armhfp]
fas = [ "cwickert", "mtasaka" ]
maintainers = [ "Christoph Wickert", "Mamoru TASAKA" ]

[spins.soas.x86_64]
fas = [ "chimosky", "aperezbios", "pbrobinson" ]
maintainers = [ "Chihurumnaya Ibiam", "Alex Perez", "Peter Robinson" ]
[spins.soas.armhfp]
fas = [ "chimosky", "aperezbios", "pbrobinson" ]
maintainers = [ "Chihurumnaya Ibiam", "Alex Perez", "Peter Robinson" ]

[labs.astronomy_kde.x86_64]
fas = [ "lupinix" ]
maintainers = [ "Christian Dersch" ]

[labs.security.x86_64]
fas = [ "fab", "jsimon" ]
maintainers = [ "Fabian Affolter", "Joerg Simon" ]

[labs.comp_neuro.x86_64]
fas = [ "bt0dotninja", "dan1mal", "ankursinha", "neuro-sig" ]
maintainers = [ "Alberto Rodriguez Sanchez", "Danny Lee", "Ankur Sinha", "NeuroFedora SIG" ]

[labs.design_suite.x86_64]
fas = [ "luya" ]
maintainers = [ "Luya Tshimbalanga" ]

[labs.games.x86_64]
fas = [ "dagostinelli" ]
maintainers = [ "Darryl T. Agostinelli" ]

[labs.jam_kde.x86_64]
fas = [ "eeickmeyer" ]
maintainers = [ "Erich Eickmeyer" ]

[labs.python_classroom.x86_64]
fas = [ "churchyard", "python-sig" ]
maintainers = [ "Miro Hrončok", "Python SIG" ]

[labs.scientific_kde.x86_64]
fas = [ "scitech" ]
maintainers = [ "SciTech SIG" ]

[labs.scientific.x86_64]
fas = [ "scitech" ]
maintainers = [ "SciTech SIG" ]

[labs.robotics.x86_64]
fas = [ "rmattes", "robotics-sig" ]
maintainers = [ "Rich Mattes", "Robotics SIG" ]

[spins.i3.x86_64]
fas = [ "jflory7", "defolos", "nasirhm", "odilhao", "x3mboy" ]
maintainers = [ "Justin Flory", "Dan Čermák", "Nasir Hussain", "Odilon Junior", "Eduard Lucena" ]
